# Generated by Django 4.1.3 on 2024-01-31 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_admission', models.DateField()),
                ('date_of_graduation', models.DateField()),
                ('award_title', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=50)),
                ('overall_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma_app.module', unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_number', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('semester_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma_app.enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma_app.module')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soma_app.student'),
        ),
    ]
