# Generated by Django 5.0.1 on 2024-02-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='award_title',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='overall_gpa',
        ),
        migrations.RemoveField(
            model_name='semesterresult',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='semesterresult',
            name='semester_gpa',
        ),
        migrations.AddField(
            model_name='course',
            name='award_title',
            field=models.CharField(default="Bachelor's Degree", max_length=100),
            preserve_default=False,
        ),
    ]
