# Generated by Django 5.0.1 on 2024-02-06 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma_app', '0006_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterresult',
            name='student',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='soma_app.student'),
            preserve_default=False,
        ),
    ]
