# Generated by Django 5.0.1 on 2024-02-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soma_app', '0007_semesterresult_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModule',
        ),
    ]
