# Generated by Django 5.0.1 on 2024-02-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soma_app', '0010_student_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='modules',
        ),
    ]
