# Generated by Django 5.0.1 on 2024-02-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soma_app', '0012_alter_semesterresult_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semesterresult',
            unique_together=set(),
        ),
    ]
