# Generated by Django 5.0.1 on 2024-02-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soma_app', '0015_remove_semesterresult_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
